export const seniorBuddies = [
  {
    id: 's1',
    role: 'senior',
    name: 'Anna Müller',
    age: 26,
    studyProgram: 'Management & Technology (MUT)',
    relatedPrograms: ['Management', 'Technology Management'],
    interests: ['startups', 'hiking', 'board games', 'mentoring'],
    bio: 'Passionate about entrepreneurship and helping new students arrive at TUM Campus Heilbronn.',
    bioKeywords: ['entrepreneurship', 'orientation', 'support', 'Heilbronn'],
    avatarColor: 'bg-blue-700',
  },
  {
    id: 's2',
    role: 'senior',
    name: 'Luca Schneider',
    age: 28,
    studyProgram: 'Information Systems',
    relatedPrograms: ['Computer Science', 'Data Engineering'],
    interests: ['coding', 'basketball', 'coffee', 'hackathons'],
    bio: 'Working student in a local tech company, happy to support with tech courses and exams.',
    bioKeywords: ['tech', 'exams', 'coding', 'projects'],
    avatarColor: 'bg-emerald-600',
  },
  {
    id: 's3',
    role: 'senior',
    name: 'Sofia Rossi',
    age: 25,
    studyProgram: 'Management',
    relatedPrograms: ['Management & Technology (MUT)', 'Entrepreneurship'],
    interests: ['marketing', 'yoga', 'cooking', 'events'],
    bio: 'I love organizing small events and meetups and know the best study spots on campus.',
    bioKeywords: ['events', 'meetups', 'study spots', 'campus life'],
    avatarColor: 'bg-rose-500',
  },
  {
    id: 's4',
    role: 'senior',
    name: 'David Kim',
    age: 27,
    studyProgram: 'Data Engineering',
    relatedPrograms: ['Information Systems', 'Computer Science'],
    interests: ['data science', 'machine learning', 'cycling', 'movies'],
    bio: 'Data nerd who enjoys explaining complex topics in a simple way.',
    bioKeywords: ['data', 'machine learning', 'statistics', 'tutoring'],
    avatarColor: 'bg-amber-500',
  },
  {
    id: 's5',
    role: 'senior',
    name: 'Elena Petrova',
    age: 29,
    studyProgram: 'Entrepreneurship',
    relatedPrograms: ['Management', 'Management & Technology (MUT)'],
    interests: ['startups', 'design thinking', 'reading', 'travel'],
    bio: 'Co-founded a student initiative and love connecting people with similar ideas.',
    bioKeywords: ['networking', 'startups', 'ideas', 'initiative'],
    avatarColor: 'bg-indigo-600',
  },
  {
    id: 's6',
    role: 'senior',
    name: 'Jonas Weber',
    age: 27,
    studyProgram: 'BMDS (B.Sc.)',
    relatedPrograms: ['BiE (B.Sc.)'],
    interests: ['data science', 'basketball', 'board games'],
    bio: 'Enjoys explaining statistics and data projects in an accessible way.',
    bioKeywords: ['data', 'statistics', 'projects', 'support'],
    avatarColor: 'bg-sky-700',
  },
  {
    id: 's7',
    role: 'senior',
    name: 'Hannah Krause',
    age: 25,
    studyProgram: 'BiE (B.Sc.)',
    relatedPrograms: ['BMDS (B.Sc.)'],
    interests: ['software engineering', 'running', 'coffee'],
    bio: 'Knows the best running routes around campus and likes building web apps.',
    bioKeywords: ['running', 'web', 'projects'],
    avatarColor: 'bg-teal-600',
  },
  {
    id: 's8',
    role: 'senior',
    name: 'Paul Fischer',
    age: 29,
    studyProgram: 'MiE (M.Sc.)',
    relatedPrograms: ['MIM (M.Sc.)'],
    interests: ['consulting', 'case competitions', 'reading'],
    bio: 'Active in consulting clubs and happy to share insights on applications.',
    bioKeywords: ['consulting', 'case competitions', 'applications'],
    avatarColor: 'bg-stone-600',
  },
  {
    id: 's9',
    role: 'senior',
    name: 'Laura Hoffmann',
    age: 26,
    studyProgram: 'MMDT (M.Sc.)',
    relatedPrograms: ['MiE (M.Sc.)'],
    interests: ['digital technology', 'product management', 'yoga'],
    bio: 'Interested in digital products and keeping a good study-life balance.',
    bioKeywords: ['digital', 'product', 'balance'],
    avatarColor: 'bg-purple-600',
  },
  {
    id: 's10',
    role: 'senior',
    name: 'Marco Conti',
    age: 28,
    studyProgram: 'MIM (M.Sc.)',
    relatedPrograms: ['MiE (M.Sc.)'],
    interests: ['strategy', 'startups', 'football'],
    bio: 'Combines strategic thinking with a passion for football and team events.',
    bioKeywords: ['strategy', 'team', 'events'],
    avatarColor: 'bg-red-500',
  },
  {
    id: 's11',
    role: 'senior',
    name: 'Sophia Nguyen',
    age: 27,
    studyProgram: 'BMDS (B.Sc.)',
    relatedPrograms: ['BiE (B.Sc.)'],
    interests: ['machine learning', 'volunteering', 'music'],
    bio: 'Helps organize volunteering initiatives and enjoys ML side projects.',
    bioKeywords: ['volunteering', 'machine learning', 'projects'],
    avatarColor: 'bg-emerald-500',
  },
  {
    id: 's12',
    role: 'senior',
    name: 'Ali Reza',
    age: 30,
    studyProgram: 'BiE (B.Sc.)',
    relatedPrograms: ['BMDS (B.Sc.)'],
    interests: ['cloud computing', 'gaming', 'basketball'],
    bio: 'Works part-time in cloud development and likes casual basketball games.',
    bioKeywords: ['cloud', 'development', 'basketball'],
    avatarColor: 'bg-cyan-700',
  },
  {
    id: 's13',
    role: 'senior',
    name: 'Julia Braun',
    age: 24,
    studyProgram: 'MiE (M.Sc.)',
    relatedPrograms: ['MIM (M.Sc.)'],
    interests: ['marketing', 'events', 'photography'],
    bio: 'Experienced in organizing campus events and loves photography projects.',
    bioKeywords: ['events', 'photography', 'marketing'],
    avatarColor: 'bg-pink-600',
  },
  {
    id: 's14',
    role: 'senior',
    name: 'Tim Schuster',
    age: 26,
    studyProgram: 'MMDT (M.Sc.)',
    relatedPrograms: ['MiE (M.Sc.)'],
    interests: ['software engineering', 'hackathons', 'running'],
    bio: 'Participates in hackathons and enjoys long-distance running.',
    bioKeywords: ['hackathons', 'software', 'running'],
    avatarColor: 'bg-orange-600',
  },
  {
    id: 's15',
    role: 'senior',
    name: 'Elif Yılmaz',
    age: 27,
    studyProgram: 'MIM (M.Sc.)',
    relatedPrograms: ['MiE (M.Sc.)'],
    interests: ['finance', 'reading', 'yoga'],
    bio: 'Interested in sustainable finance and mental well-being.',
    bioKeywords: ['finance', 'sustainable', 'well-being'],
    avatarColor: 'bg-lime-700',
  },
  {
    id: 's16',
    role: 'senior',
    name: 'Matteo Romano',
    age: 25,
    studyProgram: 'BMDS (B.Sc.)',
    relatedPrograms: ['BiE (B.Sc.)'],
    interests: ['sports', 'board games', 'travel'],
    bio: 'Enjoys organizing casual sports meetups and game nights.',
    bioKeywords: ['sports', 'games', 'meetups'],
    avatarColor: 'bg-blue-500',
  },
  {
    id: 's17',
    role: 'senior',
    name: 'Anika Shah',
    age: 28,
    studyProgram: 'BiE (B.Sc.)',
    relatedPrograms: ['BMDS (B.Sc.)'],
    interests: ['research', 'data science', 'libraries'],
    bio: 'Knows the quietest study spots and how to approach research projects.',
    bioKeywords: ['research', 'libraries', 'data'],
    avatarColor: 'bg-rose-600',
  },
  {
    id: 's18',
    role: 'senior',
    name: 'Felix Wagner',
    age: 27,
    studyProgram: 'MiE (M.Sc.)',
    relatedPrograms: ['MIM (M.Sc.)'],
    interests: ['case competitions', 'public speaking', 'running'],
    bio: 'Active in debate clubs and enjoys supporting presentation skills.',
    bioKeywords: ['public speaking', 'competitions', 'debate'],
    avatarColor: 'bg-yellow-600',
  },
  {
    id: 's19',
    role: 'senior',
    name: 'Nora König',
    age: 26,
    studyProgram: 'MMDT (M.Sc.)',
    relatedPrograms: ['MiE (M.Sc.)'],
    interests: ['UX design', 'music', 'yoga'],
    bio: 'Combines UX interests with a passion for music and mindfulness.',
    bioKeywords: ['ux', 'design', 'music'],
    avatarColor: 'bg-fuchsia-600',
  },
  {
    id: 's20',
    role: 'senior',
    name: 'Daniel Ortiz',
    age: 29,
    studyProgram: 'MIM (M.Sc.)',
    relatedPrograms: ['MiE (M.Sc.)'],
    interests: ['startups', 'networking', 'football'],
    bio: 'Enjoys connecting people at networking events and startup meetups.',
    bioKeywords: ['networking', 'startups', 'events'],
    avatarColor: 'bg-indigo-700',
  },
]

export const juniorBuddies = [
  {
    id: 'j1',
    role: 'junior',
    name: 'Maximilian Bauer',
    age: 20,
    studyProgram: 'Management & Technology (MUT)',
    relatedPrograms: ['Management', 'Technology Management'],
    interests: ['startups', 'basketball', 'board games'],
    bio: 'First semester student, new to Heilbronn and looking for people to build projects with.',
    bioKeywords: ['projects', 'new in town', 'orientation'],
    avatarColor: 'bg-sky-500',
  },
  {
    id: 'j2',
    role: 'junior',
    name: 'Li Wei',
    age: 22,
    studyProgram: 'Information Systems',
    relatedPrograms: ['Computer Science'],
    interests: ['coding', 'gaming', 'coffee'],
    bio: 'Excited about building web apps and learning more about the German working culture.',
    bioKeywords: ['web', 'culture', 'career'],
    avatarColor: 'bg-sky-500',
  },
  {
    id: 'j3',
    role: 'junior',
    name: 'Fatima Khan',
    age: 21,
    studyProgram: 'Management',
    relatedPrograms: ['Entrepreneurship'],
    interests: ['marketing', 'events', 'yoga'],
    bio: 'Interested in marketing and student clubs. I want to get involved on campus quickly.',
    bioKeywords: ['clubs', 'marketing', 'events'],
    avatarColor: 'bg-fuchsia-500',
  },
  {
    id: 'j4',
    role: 'junior',
    name: 'Jonas Richter',
    age: 23,
    studyProgram: 'Data Engineering',
    relatedPrograms: ['Information Systems'],
    interests: ['data science', 'cycling', 'board games'],
    bio: 'Switched from mechanical engineering and happy to meet people with similar interests.',
    bioKeywords: ['career change', 'data', 'support'],
    avatarColor: 'bg-lime-600',
  },
  {
    id: 'j5',
    role: 'junior',
    name: 'Maria Lopez',
    age: 19,
    studyProgram: 'Entrepreneurship',
    relatedPrograms: ['Management'],
    interests: ['startups', 'reading', 'travel'],
    bio: 'I want to explore the startup ecosystem in Heilbronn and Munich.',
    bioKeywords: ['startup ecosystem', 'networking'],
    avatarColor: 'bg-orange-500',
  },
  {
    id: 'j6',
    role: 'junior',
    name: 'Omar Ahmed',
    age: 24,
    studyProgram: 'Information Systems',
    relatedPrograms: ['Data Engineering'],
    interests: ['machine learning', 'football', 'coffee'],
    bio: 'Looking for someone who can recommend good courses and projects to focus on.',
    bioKeywords: ['courses', 'projects', 'recommendations'],
    avatarColor: 'bg-cyan-600',
  },
  {
    id: 'j7',
    role: 'junior',
    name: 'Sarah Johnson',
    age: 20,
    studyProgram: 'Management & Technology (MUT)',
    relatedPrograms: ['Management'],
    interests: ['events', 'cooking', 'yoga'],
    bio: 'I love social events and would like to join student initiatives.',
    bioKeywords: ['events', 'initiatives', 'social'],
    avatarColor: 'bg-pink-500',
  },
  {
    id: 'j8',
    role: 'junior',
    name: 'Takashi Yamamoto',
    age: 22,
    studyProgram: 'Computer Science',
    relatedPrograms: ['Information Systems'],
    interests: ['hackathons', 'gaming', 'anime'],
    bio: 'Exchange student who wants to understand how studying in Germany works.',
    bioKeywords: ['exchange', 'orientation', 'language'],
    avatarColor: 'bg-slate-700',
  },
  {
    id: 'j9',
    role: 'junior',
    name: 'Laura Schmidt',
    age: 21,
    studyProgram: 'Management',
    relatedPrograms: ['Entrepreneurship', 'Management & Technology (MUT)'],
    interests: ['reading', 'board games', 'events'],
    bio: 'Interested in case competitions and consulting clubs.',
    bioKeywords: ['consulting', 'case competitions', 'clubs'],
    avatarColor: 'bg-violet-600',
  },
  {
    id: 'j10',
    role: 'junior',
    name: 'Nikhil Verma',
    age: 23,
    studyProgram: 'Data Engineering',
    relatedPrograms: ['Information Systems', 'Computer Science'],
    interests: ['data science', 'startups', 'cricket'],
    bio: 'I enjoy working with data and want to connect with people doing similar projects.',
    bioKeywords: ['data', 'projects', 'networking'],
    avatarColor: 'bg-emerald-700',
  },
]

export const activitiesSeed = [
  {
    id: 'a1',
    title: 'Welcome Walk around Heilbronn',
    description:
      'Easy city walk to show new students around Heilbronn, including campus, Neckar, and favorite coffee spots.',
    dateTime: '2026-04-05T16:00',
    location: 'TUM Campus Heilbronn main entrance',
    interests: ['hiking', 'events', 'coffee', 'new in town'],
    participants: ['s1', 'j1', 'j3'],
  },
  {
    id: 'a2',
    title: 'Startup Ideation Night',
    description:
      'Informal evening to brainstorm startup ideas in small groups. No prior experience required.',
    dateTime: '2026-04-10T18:30',
    location: 'Innovation Space, Bildungscampus',
    interests: ['startups', 'entrepreneurship', 'design thinking'],
    participants: ['s1', 's5', 'j1', 'j5', 'j10'],
  },
  {
    id: 'a3',
    title: 'Data & Pizza Study Session',
    description:
      'Joint study evening for Information Systems and Data Engineering students – bring your questions.',
    dateTime: '2026-04-15T19:00',
    location: 'Learning Center, Group Room 3',
    interests: ['data science', 'machine learning', 'coding'],
    participants: ['s2', 's4', 'j2', 'j4', 'j6', 'j10'],
  },
]

export const initialMessages = [
  {
    id: 'm1',
    from: 's1',
    to: 'j1',
    timestamp: '2026-03-10T10:00',
    text: 'Hi Maximilian, welcome to TUM Campus Heilbronn! Happy to help you settle in.',
  },
  {
    id: 'm2',
    from: 'j1',
    to: 's1',
    timestamp: '2026-03-10T10:05',
    text: 'Hi Anna, thanks a lot! I would love some tips on good study places.',
  },
  {
    id: 'm3',
    from: 's2',
    to: 'j2',
    timestamp: '2026-03-11T15:30',
    text: 'Hey Li, if you like web apps, I can recommend a few projects and courses.',
  },
]

